AllCops:
  DisabledByDefault: true
  Exclude:
    - 'bin/**/*'
    - 'config/**/*'
    - 'db/**/*'
    - 'docs/**/*'
    - 'log/**/*'
    - 'public/**/*'
    - 'scripts/**/*'
    - 'sketch/**/*'
    - 'vendor/**/*'
    - 'x2_export/**/*'
    - spec/teaspoon_env.rb

Layout/TrailingWhitespace:
  Enabled: true

Layout/TrailingBlankLines:
  Enabled: true

Layout/BlockEndNewline:
  Enabled: true
