language: ruby
rvm:
  - ruby-2.3.0

sudo: required

services:
  - postgres

branches:
  only:
    - master

# For AWS deploy, install the AWS CLI, so we can push asset artifacts up to S3 when merging to master.
# before_install:
#   - pip install --user awscli
#   - export PATH=$PATH:$HOME/.local/bin

before_install:
  - export TZ=America/New_York
  - echo psql --version
  - gem install -v 1.10.6 bundler --no-rdoc --no-ri

  # workarounds for phantomjs 1, see: https://github.com/travis-ci/travis-ci/issues/3225#issuecomment-177592725
  - mkdir travis-phantomjs
  - wget https://studentinsights-public.s3.amazonaws.com/phantomjs-2.1.1-linux-x86_64.tar.bz2 -O $PWD/travis-phantomjs/phantomjs-2.1.1-linux-x86_64.tar.bz2
  - tar -xvf $PWD/travis-phantomjs/phantomjs-2.1.1-linux-x86_64.tar.bz2 -C $PWD/travis-phantomjs
  - export PATH=$PWD/travis-phantomjs/phantomjs-2.1.1-linux-x86_64/bin:$PATH

  # install newer version of node
  - . $HOME/.nvm/nvm.sh
  - nvm install stable
  - nvm use stable
  - npm install
  - node --version
  - npm --version
  - npm install

install:
 - bundle _1.10.6_ install --retry=3

script:
  - npm run lint-cli
  - bundle exec rake db:create db:migrate DATABASE_URL=postgres://localhost/student_insights_test
  - bundle exec rspec spec
  - bundle exec teaspoon
  - rubocop
