somerville:
  remote_filenames:
    - FILENAME_FOR_STUDENTS_IMPORT: students_export.txt
    - FILENAME_FOR_EDUCATORS_IMPORT: educators_export.txt
    - FILENAME_FOR_BEHAVIOR_IMPORT: behavior_export.txt
    - FILENAME_FOR_ASSESSMENT_IMPORT: assessment_export.txt
    - FILENAME_FOR_ATTENDANCE_IMPORT: attendance_export.txt
    - FILENAME_FOR_STUDENT_AVERAGES_IMPORT: student_averages_export.txt
    - FILENAME_FOR_COURSE_SECTION_IMPORT: courses_sections_export.txt
    - FILENAME_FOR_STUDENTS_SECTION_ASSIGNMENT_IMPORT: student_section_assignment_export.txt
    - FILENAME_FOR_EDUCATOR_SECTION_ASSIGNMENT_IMPORT: educator_section_assignment_export.txt
    - FILENAME_FOR_STAR_READING_IMPORT: SomervillePublicSchools\ -\ Generic\ SR\ Pipeline\ Extract\ -\ Active.csv
    - FILENAME_FOR_STAR_MATH_IMPORT: SomervillePublicSchools\ -\ Generic\ SM\ Pipeline\ Extract\ -\ Active.csv
  schools:
    -
      local_id: BRN
      name: Benjamin G Brown
      school_type: ES
    -
      local_id: HEA
      name: Arthur D Healey
      school_type: ESMS
    -
      local_id: KDY
      name: John F Kennedy
      school_type: ESMS
    -
      local_id: AFAS
      name: Albert F. Argenziano School
      school_type: ESMS
    -
      local_id: ESCS
      name: E Somerville Community
      school_type: ESMS
    -
      local_id: WSNS
      name: West Somerville Neighborhood
      school_type: ESMS
    -
      local_id: WHCS
      name: Winter Hill Community
      school_type: ESMS
    -
      local_id: NW
      name: Next Wave Junior High
      school_type: MS
    -
      local_id: SHS
      name: Somerville High
      school_type: HS
    -
      local_id: FC
      name: Full Circle High School
      school_type: HS
    -
      local_id: CAP
      name: Capuano Early Childhood Center
    -
      local_id: PIC
      name: Parent Information Center
    -
      local_id: SPED
      name: Special Education

new-bedford:
  schools:
    -
      name: Charles S. Ashley
      local_id: '010'
    -
      name: Elizabeth Carter Brooks
      local_id: '015'
    -
      name: Elwyn G. Campbell
      local_id: '020'
    -
      name: Sgt. William Carney Memorial Academy
      local_id: '045'
    -
      name: James B. Congdon
      local_id: '040'
    -
      name: John B. DeValles
      local_id: '050'
    -
      name: Alfred J. Gomes
      local_id: '063'
    -
      name: Irwin M. Jacobs
      local_id: '070'
    -
      name: Ellen R. Hathaway
      local_id: '075'
    -
      name: Hayden-McFadden
      local_id: '078'
    -
      name: Abraham Lincoln
      local_id: '095'
    -
      name: Carlos Pacheco
      local_id: '105'
    -
      name: John A. Parker
      local_id: '115'
    -
      name: Casimir Pulaski
      local_id: '105'
    -
      name: Renaissance
      local_id: '124'
    -
      name: Thomas R. Rodman
      local_id: '125'
    -
      name: Jireh Swift
      local_id: '130'
    -
      name: William H. Taylor
      local_id: '135'
    -
      name: Betsey B. Winslow
      local_id: '140'
    -
      name: Keith Middle
      local_id: '405'
    -
      name: Normandin Middle
      local_id: '410'
    -
      name: Roosevelt Middle
      local_id: '415'
    -
      name: New Bedford High
      local_id: '505'
    -
      name: Trinity Day Academy
      local_id: '510'
    -
      name: Whaling City Jr./Sr. High
      local_id: '515'

