# This is based off https://docs.docker.com/compose/rails/
studentinsights:
  build: .
  volumes:
    - .:/mnt/somerville-teacher-tool
  working_dir: /mnt/somerville-teacher-tool
  environment:
    DATABASE_URL: postgresql://postgres@postgres # overrides hostname and username
  ports:
    - "3000:3000"
    - "4000:4000"
  links:
    - postgres
  # This runs two separate processes concurrently, dying when either dies.
  # This is how we run things locally, so just replicating within the container
  # so our configuration is the same, rather than splitting separate containers.
  command: yarn start 

postgres:
  image: postgres
  ports:
    - "5432:5432"
  volumes:
    - /var/lib/postgresql/data